=== bionlplab/bioc/schema/bioc_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "definitions": {
    "annotation": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "infons": {
          "type": "object"
        },
        "text": {
          "type": "string"
        },
        "locations": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "offset": {
                  "type": "integer"
                },
                "length": {
                  "type": "integer"
                }
              },
              "required": [
                "offset",
                "length"
              ]
            }
          ]
        }
      },
      "required": [
        "id",
        "text",
        "locations"
      ]
    },
    "relation": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "infons": {
          "type": "object"
        },
        "nodes": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "refid": {
                "type": "string"
              },
              "role": {
                "type": "string"
              }
            },
            "required": [
              "refid",
              "role"
            ]
          }
        }
      },
      "required": [
        "id",
        "nodes"
      ]
    }
  },
  "properties": {
    "source": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "key": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "infons": {
      "type": "object"
    },
    "documents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "infons": {
            "type": "object"
          },
          "passages": {
            "type": "array",
            "items": {
              "properties": {
                "offset": {
                  "type": "integer"
                },
                "infons": {
                  "type": "object"
                },
                "text": {
                  "type": "string"
                },
                "sentences": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "offset": {
                        "type": "integer"
                      },
                      "infons": {
                        "type": "object"
                      },
                      "text": {
                        "type": "string"
                      },
                      "annotations": {
                        "type": "array",
                        "items": {
                          "$ref": "#/definitions/annotation"
                        }
                      },
                      "relations": {
                        "type": "array",
                        "items": {
                          "$ref": "#/definitions/relation"
                        }
                      }
                    },
                    "required": [
                      "offset",
                      "text"
                    ]
                  }
                },
                "annotations": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/annotation"
                  }
                },
                "relations": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/relation"
                  }
                }
              },
              "required": [
                "offset"
              ]
            }
          },
          "annotations": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/annotation"
            }
          },
          "relations": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/relation"
            }
          }
        },
        "required": [
          "id",
          "passages"
        ]
      }
    }
  },
  "required": [
    "source",
    "date",
    "key",
    "documents"
  ]
}

=== bionlplab/bioc/tests/biocjson/everything.json
{
  "source": "source",
  "date": "date",
  "key": "key",
  "infons": {
    "collection-infon-key": "collection-infon-value"
  },
  "documents": [
    {
      "id": "1",
      "infons": {
        "document-infon-key": "document-infon-value"
      },
      "passages": [
        {
          "offset": 0,
          "infons": {
            "passage-infon-key": "passage-infon-value"
          },
          "text": "abcdefghijklmnopqrstuvwxyz",
          "sentences": [],
          "annotations": [
            {
              "id": "1",
              "infons": {
                "annotation-infon-key": "annotation-infon-value"
              },
              "text": "bc",
              "locations": [
                {
                  "offset": 1,
                  "length": 2
                }
              ]
            },
            {
              "id": "2",
              "infons": {
                "annotation-infon-key": "annotation-infon-value"
              },
              "text": "fg",
              "locations": [
                {
                  "offset": 5,
                  "length": 2
                }
              ]
            }
          ],
          "relations": [
            {
              "id": "R1",
              "infons": {
                "relation-infon-key": "relation-infon-value"
              },
              "nodes": [
                {
                  "refid": "1",
                  "role": "role1"
                },
                {
                  "refid": "2",
                  "role": "role2"
                }
              ]
            }
          ]
        }
      ],
      "annotations": [],
      "relations": [
        {
          "id": "R2",
          "infons": {
            "relation-infon-key": "relation-infon-value"
          },
          "nodes": [
            {
              "refid": "1",
              "role": "role1"
            },
            {
              "refid": "2",
              "role": "role2"
            }
          ]
        }
      ]
    },
    {
      "id": "2",
      "infons": {},
      "passages": [
        {
          "offset": 27,
          "infons": {},
          "text": "",
          "sentences": [
            {
              "offset": 27,
              "infons": {
                "sentence-infon-key": "sentence-infon-value"
              },
              "text": "abcdefg",
              "annotations": [
                {
                  "id": "3",
                  "infons": {
                    "annotation-infon-key": "annotation-infon-value"
                  },
                  "text": "bc",
                  "locations": [
                    {
                      "offset": 28,
                      "length": 2
                    }
                  ]
                }
              ],
              "relations": [
                {
                  "id": "R3",
                  "infons": {
                    "relation-infon-key": "relation-infon-value"
                  },
                  "nodes": [
                    {
                      "refid": "3",
                      "role": "role1"
                    }
                  ]
                }
              ]
            },
            {
              "offset": 34,
              "infons": {
                "sentence-infon-key": "sentence-infon-value"
              },
              "text": "测试Non-ASCII",
              "annotations": [
                {
                  "id": "4",
                  "infons": {
                    "annotation-infon-key": "annotation-infon-value"
                  },
                  "text": "测试",
                  "locations": [
                    {
                      "offset": 34,
                      "length": 2
                    }
                  ]
                }
              ],
              "relations": []
            }
          ],
          "annotations": [],
          "relations": []
        }
      ],
      "annotations": [],
      "relations": []
    }
  ]
}
